<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/dyuuulmg0/image/upload/v1554609961/sammyy.jpg" alt="Achem Samuel">
                        <h6>Achem Samuel</h6>
                        <p>Mobile Developer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/_Achimedes" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/Achemsamuel" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@achemsamuel" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>I am an iOS developer. I consider myself a very fast learner, and a great team player. I also love taking on new challenges that test my knowledge of app development and the environment.
Alongside software development, i curate technical content for a media outfit.</p>
                        <br />
                        <h6>Skills</h6>
                        <p>Swift | HTML | Javascript</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
